version: "2"
services:
  jenkins:
    container_name: jenkins
    restart: always
    privileged: true
    image: jenkins/jenkins:lts
    user: jenkins
    ports:
      - 8087:8080
      - 443:8443
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/admin/.docker/:/home/jenkins/.docker/
    depends_on:
      - sonarqube
  sonarqube:
    image: sonarqube:6.7-alpine
    container_name: sonarqube
    ports:
      - 9098:9000
      - 9099:9092
volumes:
  jenkins_data:
